version: '3.8'

services:
  webapi:
    build:
      context: .  # التأكد من أن السياق يشير إلى المجلد الجذر
      dockerfile: ./prod/Dockerfile
    env_file: ./prod/.env.prod
    ports:
      - "80:80"