name: .NET CI (Development)

on:
  pull_request:
    branches: [development]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/DockerApi/DockerApi.csproj

      - name: Build
        run: dotnet build src/DockerApi/DockerApi.csproj --configuration Debug --no-restore

      - name: Test
        run: dotnet test src/DockerApi/DockerApi.csproj --configuration Debug --no-restore --no-build

      - name: Docker Build
        run: docker-compose -f docker-compose.dev.yml build